apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: <CI_ENVIRONMENT_SLUG>-<CI_PROJECT_NAME>
  namespace: <KUBE_NAMESPACE>
  annotations:
    app.gitlab.com/app: <CI_PROJECT_PATH_SLUG>
    app.gitlab.com/env: <CI_ENVIRONMENT_SLUG>
  labels:
    app: <CI_PROJECT_NAME>
    tier: ui
    pipeline_id: "<CI_PIPELINE_ID>"
    build_id: "<CI_BUILD_ID>"
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: <CI_PROJECT_NAME>
      tier: ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app.gitlab.com/app: <CI_PROJECT_PATH_SLUG>
        app.gitlab.com/env: <CI_ENVIRONMENT_SLUG>
      labels:
        app: <CI_PROJECT_NAME>
        tier: ui
        pipeline_id: "<CI_PIPELINE_ID>"
        build_id: "<CI_BUILD_ID>"
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: <CI_PROJECT_NAME>
        image: <CI_REGISTRY_IMAGE>:<CI_COMMIT_REF_SLUG>
        imagePullPolicy: Always
        env:
        - name: API_URL
          value: "/api/v1/graphql"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: <CI_PROJECT_NAME>
  namespace: <KUBE_NAMESPACE>
  annotations:
    app.gitlab.com/app: <CI_PROJECT_PATH_SLUG>
    app.gitlab.com/env: <CI_ENVIRONMENT_SLUG>
  labels:
    app: <CI_PROJECT_NAME>
    tier: ui
    pipeline_id: "<CI_PIPELINE_ID>"
    build_id: "<CI_BUILD_ID>"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: <CI_PROJECT_NAME>
    tier: ui
  sessionAffinity: None
  type: ClusterIP